import { z } from "zod";

export const MunicipalitySchema = z.object({
  id: z.string(),
  slug: z.string().optional(),
  fipsCode: z.string(),
  gnisId: z.string(),
  name: z.string(),
  type: z.enum(["City", "Village", "Town", "CDP"]),
  county: z.string(),
  incorporationStatus: z.enum(["Incorporated", "Unincorporated"]),
  incorporationDate: z.string().optional(),
  coordinates: z.object({
    lat: z.number(),
    lng: z.number(),
  }),
  boundaries: z.any().optional(),
  landArea: z.number(),
  waterArea: z.number(),
  totalArea: z.number(),
  elevation: z.number(),
  population: z.object({
    current: z.number(),
    census2020: z.number(),
    census2010: z.number(),
    census2000: z.number(),
    census1990: z.number().optional(),
    estimateYear: z.number().optional(),
    growthRate: z.number(),
    density: z.number(),
  }),
  economics: z.object({
    medianHouseholdIncome: z.number(),
    medianFamilyIncome: z.number().optional(),
    perCapitaIncome: z.number().optional(),
    medianHomeValue: z.number(),
    medianRent: z.number().optional(),
    povertyRate: z.number(),
    unemploymentRate: z.number(),
  }),
  demographics: z.any().optional(),
  government: z.object({
    type: z.string(),
    mayor: z.union([z.string(), z.object({ name: z.string().optional(), party: z.string().optional(), termEnds: z.string().optional() })]).optional(),
    website: z.string().url().optional(),
    phone: z.string().optional(),
    address: z.union([
      z.string(),
      z.object({ street: z.string().optional(), city: z.string().optional(), state: z.string().optional(), zip: z.string().optional() })
    ]).optional(),
    cityCouncilSize: z.number().optional(),
  }),
  taxes: z.object({
    salesTaxRate: z.number().optional(),
    propertyTaxRate: z.number().optional(),
    incomeTaxLocal: z.number().optional(),
    businessTax: z.string().optional(),
  }).optional(),
  infrastructure: z.any().optional(),
  history: z.any().optional(),
  links: z.any().optional(),
  lastUpdated: z.string(),
  dataSource: z.string(),
  searchTokens: z.string(),
});